Data_Preparation:
  test_size: 0.25
  random_state: 42

Train:
  Random_Forest:
    n_estimators: 128
    max_depth: 13
    max_features: null
    min_samples_split: 5
    min_samples_leaf: 5
    max_samples: 0.7115020945504928
    criterion: 'squared_error'
    verbose: 1
    n_jobs: -1
  
  LightGBM:
    n_estimators: 78
    max_depth: 28
    learning_rate: 0.2658866008990233
    subsample: 0.5287157349748149
    min_child_weight: 7
    min_split_gain: 0.008083235828674103
    reg_lambda: 83.51605012289579
    n_jobs: -1
